### PR TITLE
Update hyper crates versions

### PR DESCRIPTION
**Pull request by kirhgoff**
Adding `rollbar = "0.5.1"` crate to Cargo.toml makes project fail to compile

## Error
```
klastovirya [~/Projects/rust-buildpack-example-actix] at  add-rollbar-error-reporting !
→ cargo build                                                                                              [07d48fc]
    Blocking waiting for file lock on the registry index
    Updating crates.io index
   Compiling openssl v0.9.24
   Compiling tokio-io v0.1.12
   Compiling serde_derive v1.0.91
   Compiling tokio-threadpool v0.1.14
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/Users/klastovirya/Projects/rust-buildpack-example-actix/target/debug/build/openssl-42343e84315ca446/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /Users/klastovirya/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

## Cause
from here https://github.com/paritytech/substrate/issues/800

the problem is my openssl version is 1.1.1
it is not supported by
0.9.x of openssl crate :
https://github.com/sfackler/rust-openssl/blob/0.9.x/openssl/build.rs#L16
the problem is fixed in newer version of openssl crate :
https://github.com/sfackler/rust-openssl/blob/master/openssl/build.rs#L33

## Solution
Use the last version of the hyper crate. Replace hyper-openssl crate with hyper-tls.

### CODE REVIEW

**Comment by RoxasShadow** [comment]
Hey @kirhgoff, thank you so much for your work :) I will merge your branch as soon as tests do pass!

**Comment by kirhgoff** [comment]
@RoxasShadow yeah I am stuck a little bit with passing data from futures. Will do another effort this weekend.

**Comment by kirhgoff** [comment]
@RoxasShadow I think the fix is ready (though I haven't tested it yet in a real app, going to do it on weekend). The main problem was to find how this new hyper version is supposed to be used, they have very slim doco and all examples just print what they receive from server and do not return it. Method `send` now is completely different. 

I would appreciate if you will merge PR with "Squash and merge" action, I wasn't formulating my comments when was working, and don't like doing rebase, squash and merge from Github UI works perfectly. I changed the description so it could be pasted into a git commit comment.

**Comment by RoxasShadow** [comment]
Thank you! I will publish the updated crate in the following days!

**Comment by RoxasShadow** [comment]
Published on crates.io as `v0.6.0`.

**Pull request merged**
